### ISSUE TITLE
Refactoring and Testing Extractor

### ISSUE THREAD

**Issue by DeagleGross** [Azure/azure-api-management-devops-resource-kit#617]
Main part of refactoring merged in this PR - #649 

## Description
This is a major issue for making code test`able and clear for the extractor code flow.
Note, that the whole refactoring is done in a separate branch - [major-repo-refactoring](https://github.com/Azure/azure-api-management-devops-resource-kit/tree/major-repo-refactoring). This is done in order not to confuse end-users - they still will be able to use the latest main, but after refactoring this will be merged into main and new version will be released.

## Plan of work
- [x] #625 setup tests with Moq for `PolicyExtractor`. Cleaned up the code and renamed most of properties in sln (from lowercase to default and proper naming). It is needed to use `JsonExtensions` for using special json-serialization-settings (_must be careful to change all serialization\deserialization - it is a breaking change_)
- [x] #631 dependency injection, migrated from [McMaster](https://github.com/natemcmaster/CommandLineUtils) to [CommandLineParser](https://github.com/commandlineparser/commandline), got rid of external library dependencies in business logic and of unnecessary reflection (and other "magic code") usage. Cleared the execution of entry point of program.
- [x] refactor apiVersionSetExtractor #643 
- [ ] refactor backendExtractor **created a separate issue** #655 
- [ ] refactor loggerExtractor **created a separate issue** #656
- [x] refactor apiExtractor #644
- [x] refactor authorizationServerExtractor #643 
- [x] refactor productExtractor #639 
- [x] refactor productApiExtractor #636 
- [x] refactor apiTagExtractor #644 
- [x] refactor tagExtractor #644
- [ ] refactor namedValueExtractor **created a separate issue** #657
- [ ] refactor masterTemplateExtractor **created a separate issue** #658

## More specific code related tasks
- [ ] remove EntityExtractorBase
- [ ] [link](https://github.com/Azure/azure-api-management-devops-resource-kit/pull/625#discussion_r809727931) change to more easy looking params
- [ ] remove all explicit `JsonConvert` calls and use `JsonExtesnions` API instead
- [x] [link](https://github.com/Azure/azure-api-management-devops-resource-kit/pull/625#discussion_r809782401) move TemplateCreator to a better place (it is bad to leave it as a static class)
- [ ] make extractors being inherited from `TemplateGeneratorBase`
- [x] use Template Builder for templates generation presets

## Extractor Architecture

- `ExtractorConsoleAppConfiguration` contains parameters for console-app (mostly fields are just strings because of cmd dependency)
- `ExtractorParameters` is a parameters collection. They are not changing during execution, only passed for using them in extractors.
- [ExtractorExecutor](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs) gets `ExtractorParameters` and is an entry point for extractor code flow basically. It instantiates a lot of different specific Extractors i.e. `policyExtractor`.
- Any specific extractor (i.e. policyExtractor) implements an interface of specific type to expose API of extracting and generating template files. Also to separate responsibility, each extractor receives a corresponding `I<specific_type>ApiClient`, that is responsible for making REST API calls to azure basically. 

```
public class PolicyExtractor : IPolicyExtractor
{
    readonly IPolicyApiClient policyApiClient;

    public PolicyExtractor(IPolicyApiClient policyApiClient = null)
    {
        this.policyApiClient = policyApiClient ?? new PolicyApiClient();
    }

    // interface implementation
    public async Task<Template> GenerateGlobalServicePolicyTemplateAsync(ExtractorParameters extractorParameters, string baseFilesDirectory) { ... }
```

In that case it is easier for developers to maintain the code and make tests also:
```
[Fact]
public async Task GeneratePolicyTemplates_ProperlyLaysTheInformation()
{
    // arranging extractor config
    var extractorConfig = new ExtractorConfig(...);

    // getting mocked policy API (not to make any calls to azure)
    var mockedPolicyApiClient = MockPolicyApiClient.GetMockedApiClientWithDefaultValues();

    // setting extractorExecutor
    var extractorParameters = new ExtractorParameters(extractorConfig);
    var extractorExecutor = new ExtractorExecutor(extractorParameters,
        policyExtractor: new PolicyExtractor(mockedPolicyApiClient));

    // running generation of policy template
    var policyTemplate = await extractorExecutor.GeneratePolicyTemplateAsync();

    // making any checks here
    ...
```

**Comment by DeagleGross** [comment]
Created an issue for each extractor left unrefactored. We will continue working on refactoring after the release.
Moving this issue to `To Be Released` and closing it. It will be still left alive due to links from child issues
